export const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL;
export const SPOTIFY_CLIENT_ID = process.env.NEXT_PUBLIC_SPOTIFY_CLIENT_ID;
export const SPOTIFY_CLIENT_SECRET = process.env.NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET;
export const SPOTIFY_CLIENT_REDIRECT_URI = process.env.NEXT_PUBLIC_SPOTIFY_REDIRECT_URI;
export const SPOTIFY_USER_ID = process.env.NEXT_PUBLIC_SPOTIFY_USER_ID;
